### ISSUE TITLE
does not compile on macOS

### ISSUE THREAD

**Issue by qaisjp** [yaegashi/msgraph.go#11]
There are lots of files in the `beta` folder and macOS does not like it.

```
➜ go build
go build github.com/yaegashi/msgraph.go/beta: /usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64/compile: fork/exec /usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64/compile: argument list too long
```

The beta folder is auto-generated, so I would recommend folding files where related.

For example:

- `ACLModel.go` and `ACLTypeEnum.go` could be combined into one `ACL.go`
- many `AccessPackage*.go` into `AccessPackage.go`
- many more `AndroidDeviceOwner*.go` into `AndroidDeviceOwner`

Also seen in:

- https://github.com/42wim/matterbridge/commit/795a8705c3fdc5bf55e83d382e7d3ff233896a0b#r37693076
- https://l0w.dev/posts/pkg.go.dev-limitation/

**Comment by yaegashi** [comment]
Hi @qaisjp, thanks for filing this issue.

I'm working on it in #12 PR.  Could you try it out by running the following?

```console
go get -u -v github.com/yaegashi/msgraph.go/beta@pr-v0.1.2
```

**Comment by qaisjp** [comment]
Sorry for not replying earlier. After updating to v0.1.2, the problem is still not solved. Maybe it's an issue with my own system. I'll come back later with more info.

**Comment by qaisjp** [comment]
The project I was testing against had your repository forked and was using the `replace` directive. So updating to v0.1.2 was not actually using your new code. It works.

Thanks!

**Comment by qaisjp** [comment]
I was not testing against your repo, I was testing against a fork. It works! Thanks.

**Comment by KidA001** [comment]
@qaisjp I have a local forked copy as well and it is not compiling. What did you do to solve?
