### ISSUE TITLE
Unable to clear string attributes

### ISSUE THREAD

**Issue by nauxliu** [yaegashi/msgraph.go#16]
The correct way to clear a string attribute is to assign it `null` value, but in the model, struct attributes are marked as `omitempty`, which means `null` values won't be pass to the API.

Is there any workaround?

**Comment by yaegashi** [comment]
The workaround is to use `SetAddtionalData()` for that attribute you want to set `null`:

```go
package main

import (
	"os"

	json "github.com/yaegashi/msgraph.go/jsonx"
	P "github.com/yaegashi/msgraph.go/ptr"
	msgraph "github.com/yaegashi/msgraph.go/v1.0"
)

func main() {
	u := msgraph.User{
		UserPrincipalName: P.String("you@example.com"),
		DisplayName:       P.String(""),
		GivenName:         nil, // XXX: omitempty
		Surname:           nil, // XXX: omitempty
	}
	u.SetAdditionalData("surName", nil)
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	enc.Encode(u)
}
```

Result:

```
{
  "surName": null,
  "displayName": "",
  "userPrincipalName": "you@example.com"
}
```

msgraph.go utilizes [jsonx package](https://github.com/yaegashi/msgraph.go/tree/master/jsonx) which is the internal fork of the standard encoding/json package.

**Comment by nauxliu** [comment]
Thank you! It works.
