### ISSUE TITLE
How to use the Org hierarchy API

### ISSUE THREAD

**Issue by nauxliu** [yaegashi/msgraph.go#17]
https://docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&tabs=http

**Comment by yaegashi** [comment]
Could you be a bit more specific about your question?  What kind of problem do you have, and what have you done so far?

**Comment by jc-dgit** [comment]
@nauxliu Yes, it does.  You can use client secret authentication with this library.  Saying that, I've been doing so for an application.  Works fine. :smile:
