### ISSUE TITLE
Official Microsoft Graph Go SDK 

### ISSUE THREAD

**Issue by baywet** [yaegashi/msgraph.go#32]
Hello everyone 👋

Vincent here from the Microsoft Graph SDKs team. I'm reaching out to announce we're working on an official Go SDK, we haven't announced the community preview yet as there are still a number of things we need to work through, but I though I'd reach out to give you an opportunity to provide feedback before anybody else!

A few benefits from this new SDK:
- Fluent style APIs to all endpoints of the API
- Contains all the models of the API
- Is updated weekly to always be in sync with the API
- Supports [v1](https://github.com/microsoftgraph/msgraph-sdk-go) and [beta](https://github.com/microsoftgraph/msgraph-beta-sdk-go)
- Relies on [Azure identity](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity) to provide support for multiple authentication flows (you also can implement your own authentication provider)
- Provides middleware for Retry handling and Redirect handling (more to come)
- And many more features to come!

As with every pre-previews, we have a [list of known limitations](https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/1) we're working through.

We'd love for you to pop by the [repos under our org](https://github.com/microsoftgraph/msgraph-sdk-go), give it a try, and give us feedback on your experience with this new SDK.

**Comment by yaegashi** [comment]
@baywet Congrats, I'm really glad to see the official SDK finally spawn!

And I suppose msgraph.go will soon have done its job.  I'd update the repository to recommend people to migrate to the official SDK.

**Comment by jc-dgit** [comment]
> I'd update the repository to recommend people to migrate to the official SDK.

Maybe lets wait first, to ensure the Go SDK gives people what they need? :wink:

**Comment by baywet** [comment]
@jc-dgit yes, I'd recommend this group waits at least until we announce the community preview (couple of weeks) or maybe even until general availability (couple of months) before archiving/deprecating this repo.
In the meantime, I encourage all of you to give a try to the new SDK, the more people try it, the better the final version will be.
And maybe a good compromise would be to ping this issue for the time being? (and not change anything on the readme just yet)

**Comment by maisarissi** [comment]
Hello everyone 😃 
We have [announced the preview of Microsoft Graph Go SDK](https://devblogs.microsoft.com/microsoft365dev/go-developers-can-now-access-microsoft-graph-with-streamlined-authentication-and-more/).
We would love to [hear your feedback](https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/new) to make sure we are giving what you need when accessing Microsoft Graph.

**Comment by baywet** [comment]
Closing for this repo's sanity. Since my original post we've reached general availability. Thanks to everyone who tried it out!
