### ISSUE TITLE
Does it support daemon apps?

### ISSUE THREAD

**Issue by hsluoyz** [yaegashi/msgraph.go#5]
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-overview

**Comment by rikkuness** [comment]
Daemon applications "uses the standard OAuth 2.0 client credentials grant."

With this library you could use that as per documentation here https://github.com/yaegashi/msgraph.go/tree/master/msauth#client-credentials-grant

**Comment by hsluoyz** [comment]
Thanks!
